/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FetchUser
 */
export interface FetchUser {
    /**
     * 
     * @type {string}
     * @memberof FetchUser
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof FetchUser
     */
    phoneNumber: string;
}

export function FetchUserFromJSON(json: any): FetchUser {
    return FetchUserFromJSONTyped(json, false);
}

export function FetchUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): FetchUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'phoneNumber': json['phoneNumber'],
    };
}

export function FetchUserToJSON(value?: FetchUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'phoneNumber': value.phoneNumber,
    };
}

